server.port=3000

# ==============================================================================
# CONFIGURACIÓN DE BASE DE DATOS LOCAL (H2)
# ==============================================================================
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.h2.console.enabled=true

# ==============================================================================
# NUEVA CONFIGURACIÓN PARA AWS S3 (SEMANA 4)
# ==============================================================================
# Nombre del bucket de AWS S3 que usará el sistema
aws.s3.bucket-name=proyecto-sistema-cursos

# Región donde se creará el bucket (por defecto en AWS Academy)
aws.region=us-east-1
aws.accessKey=${AWS_ACCESS_KEY_ID}
aws.secretKey=${AWS_SECRET_ACCESS_KEY}
aws.sessionToken=${AWS_SESSION_TOKEN}

# ==============================================================================
# CONFIGURACIÓN DE SEGURIDAD IDAAS - AZURE AD B2C (SEMANA 5)
# ==============================================================================
# Especifica a Spring Security el servidor de validación para la autenticación
spring.security.oauth2.resourceserver.jwt.issuer-uri=REEMPLAZAR_CON_TU_URL_DE_JWT_MS